server.port: 8081

spring.profiles.active=okta

spring.main.banner-mode=off

spring.jpa.hibernate.ddl-auto=none

spring.datasource.initialization-mode=always
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/flightlog
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-32634386-admin.okta.com/oauth2/default/v1/keys