
# Okta specific OAuth 2 related properties 

spring.security.oauth2.client.registration.okta.client-name=flight-log
spring.security.oauth2.client.registration.okta.client-id=0oa5cyyjjbU1zTI3O5d7
spring.security.oauth2.client.registration.okta.client-secret=pTB6_swkgAQ41ZpMT3L5YrjKE6nORVpp6mM0Yvyn
spring.security.oauth2.client.registration.okta.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.okta.scope=openid,profile,email,flightlog.read

# You need to set the issuer correctly. It will look like https://dev-<SOME_NUMBER>.okta.com/oauth2/default
okta.oauth2.issuer=https://dev-32634386.okta.com/oauth2/default

spring.security.oauth2.client.provider.okta.authorization-uri: ${okta.oauth2.issuer}/v1/authorize
spring.security.oauth2.client.provider.okta.token-uri: ${okta.oauth2.issuer}/v1/token
spring.security.oauth2.client.provider.okta.user-info-uri: ${okta.oauth2.issuer}/v1/userinfo
spring.security.oauth2.client.provider.okta.jwk-set-uri: ${okta.oauth2.issuer}/v1/keys

# You need to make sure this Resource API is running locally at port 8081
photolibrary.resource.uri=http://localhost:8081

flightlog.authorizer=Okta
flightlog.aircraft.uri=${photolibrary.resource.uri}/fakealbums/albums
flightlog.logout.url=${okta.oauth2.issuer}/v1/logout
